namespace Smab.TTInfo.CunninghamCup.Shared.TTClubs.Models;

public sealed record Contact
(
	int Id,
	int TenantId,
	string UserId,
	User User,
	string Name,
	string Initials,
	string Description,
	string Email,
	string PhoneNumber,
	int Type,
	string FirstName,
	string LastName,
	DateTime Dob,
	int Gender,
	int Age,
	string AddressLine1,
	string AddressLine2,
	string Town,
	string County,
	string Country,
	string Postcode,
	string Source,
	string Notes,
	object Deleted,
	string FullName,
	string EmergencyName,
	string EmergencyNumber,
	string GuardianEmail,
	DateTime? MedicalAgreement,
	object Unsubscribe,
	DateTime? Completed,
	object DisplayNameVisible,
	object[] Memberships,
	object[] Groups,
	DateTime? Confirmed,
	object DefaultBookingTimeSearch,
	bool MedicalAgreementUpdate,
	string DisplayName
);
