namespace Smab.TTInfo.CunninghamCup.Shared.TTClubs.Models;

public sealed record MembershipsItem
(
	int Id,
	string Name,
	DateTime StartDate,
	DateTime EndDate,
	int Usage,
	int? UsageType,
	int Payment,
	object Interval,
	float SetupFee,
	bool Active,
	string Summary,
	string Benefits,
	string Body,
	object PreviewId,
	object HeaderId,
	float Cost,
	object RenewCost,
	object UpfrontCost,
	object UpfrontRenewCost,
	bool PayLater,
	bool AutoPaid,
	int DurationType,
	int Duration,
	int Limit,
	bool AutoRenew,
	object RenewId,
	string Eligibility,
	bool ApprovalRequired,
	bool MultiUser,
	object Deleted,
	string TermsUrl,
	string TermsText,
	DateTime Published,
	int Ordering,
	int EmailType,
	string EmailBody,
	string EmailIntro,
	bool Backdate
);
